name = "vertex-cnc-api"
compatibility_date = "2024-09-05"
main = "src/worker.js"
account_id = "ac59bcba451f212de66aef49fb66fc75"

# KV namespaces - production
kv_namespaces = [
  { binding = "ORDERS_DB", id = "292d1ab0ae884a1dbd61d903bf86a64f" },
  { binding = "TRACKING_DB", id = "deb05fbef11741aa9b2ba43ee879fc82" }
]

# R2 Bucket configuration
[[r2_buckets]]
binding = "FILE_BUCKET"
bucket_name = "vertex-cnc-files"

# Production environment variables
[vars]
ENVIRONMENT = "production"
FROM_EMAIL = "destek@vertexcnc.tr"
SUPPORT_EMAIL = "destek@vertexcnc.tr"
NOTIFICATION_EMAIL = "destek@vertexcnc.tr"
